Zad2 Tablice
ewelaD/modul9 pull request #2
Opened 2017-09-16 11:21 UTC by ewelaD

2017-09-17 12:09 UTC, michal-bootcamp requested changes
w js od linii 5 masz calosc o jedno wciecie za gleboko

2017-09-17 12:09 UTC, michal-bootcamp commented on zad2/js/scripts.js
> +		allNames.push('Marysia');
a gdyby w `newName` bylo inne imie niz Marysia?

2017-09-17 14:10 UTC, ewelaD commented
Imię 'Asia', akurat ono występuje w tablicy femaleNames więc pojawia się napis: There is Asia:)

2017-09-18 14:29 UTC, michal-bootcamp requested changes

2017-09-18 14:29 UTC, michal-bootcamp commented on zad2/js/scripts.js
> +		allNames.push('Asia');
ok, tylko bardziej uniwarsalnie byloby wrzucac do tablicy wartosc zmiennej, a nie imie na sztywno :)

2017-09-20 06:18 UTC, michal-bootcamp commented
super pomysl z promptem :1st_place_medal: :)

2017-09-20 06:18 UTC, merged